name: packer-build

on:
  workflow_call:
    inputs:
      packer_version:
        description: 'Version of Packer to use'
        required: true
        type: string
      build_name:
        description: 'Name of the build'
        required: true
        type: string

jobs:
  packer_build_job:
    runs-on: ubuntu-latest
    steps:
    - name: Print Build Information
      run: echo "Building ${{ inputs.build_name }} using Packer version ${{ inputs.packer_version }}"

    - name: Simulate Using AWS Credentials
      run: |
        echo "Using AWS Access Key ID: ${{ secrets.AWS_ACCESS_KEY_ID }}"
        echo "Using AWS Secret Access Key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}"
